# Enable mouse support
set -g mouse on

# https://dev.to/spica/foot-with-true-color-tmux-support-a-la-alacritty-25gj
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable 24-bit color for foot terminal
# set -sa terminal-overrides ",foot:Tc"
# Increase history limit
set -g history-limit 10000

# Set current path on new pane/window
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Copy tmux selection into system clipboard
setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
