add_newline = false

[cmd_duration]
format = '[$duration]($style) '

[directory]
truncation_length = 8
truncate_to_repo = false
#style = 'bold blue'
style = 'cyan'
truncation_symbol = '…/'


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
up_to_date = '✓'
format = ':[$all_status$ahead_behind]($style) '

[hostname]
#ssh_only = false
format = '[$ssh_symbol$hostname]($style) '

[line_break]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[username]
format = '[$user]($style)@'
disabled = false
#show_always = true

[status]
symbol = ''
disabled = false
