[theme]
name = "modern"
[theme.overrides]
separator = ""
info_bg = "#222D32"
info_fg = "#449CDB"
good_bg = "#222D32"
good_fg = "#99b938"
warning_bg = "#222D32"
warning_fg = "#FE7E29"

[icons]
name = "awesome"

[[block]]
block = "custom"
interval = 60
command = "test -e /var/run/reboot-required && echo reboot required"
hide_when_empty = true

[[block]]
block = "net"
device = "wlp3s0"
format = " {ip} {ipv6} {signal_strength} @ {ssid} {bitrate} {frequency}{speed_down;K*b} {speed_up;K*b}"
interval = 5
hide_inactive = true
icons_format = "{icon}"

[[block]]
block = "net"
device = "enp0s31f6"
format = " {ipv6} {ip} {bitrate} {speed_down;K*b} {speed_up;K*b}"
interval = 5
hide_inactive = true
icons_format = "{icon}"

[[block]]
block = "net"
device = "vpn0"
format = "{ip}"
interval = 10
hide_inactive = true
#format = "{ip} {speed_down;K*b} {speed_down;K*b}"
if_command = "test -e /sys/class/net/vpn0 && test \"$(cat /sys/class/net/vpn0/operstate)\" = \"up\""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{alias} {available}"

[[block]]
block = "disk_space"
path = "/var"
alias = "/var"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
format = "{alias} {available}"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{alias} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "temperature"
inputs = ["CPU"]
idle = 50
info = 70
warning = 90

[[block]]
block = "cpu"
interval = 5
format = "{utilization} {frequency} {boost}"
warning = 75
# NOTE: based on: https://www.linuxhow2.com/2021/05/05/how-to-disable-intel-turboboost-using-systemd/
on_click = "systemctl is-active --quiet disable-intel-pstate-turbo.service && sudo systemctl stop disable-intel-pstate-turbo.service || sudo systemctl start disable-intel-pstate-turbo.service"
#[block.theme_overrides]
#info_bg = "#222D32"
#info_fg = "#CFD8DC"

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.pci-0000_00_1f.3.analog-stereo"
headphones_indicator = true
format = "Int: {volume}"
show_volume_when_muted = true

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo"
device_kind = "source"
format = "Ext: {volume}"
on_click = "pactl -- set-source-mute @DEFAULT_SOURCE@ toggle"
if_command = "test $(pactl list cards | grep alsa_card.usb-Focusrite_Scarlett_2i2_USB-00 | wc -l) -ge 1"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.usb-Solid_State_System_Co._Ltd._MMX_150-00.analog-stereo"
format = "MMX: {volume}"
show_volume_when_muted = true
on_click = "pactl set-sink-mute alsa_output.usb-Solid_State_System_Co._Ltd._MMX_150-00.analog-stereo toggle"
if_command = "test $(pactl list cards short | grep MMX_150-00 | wc -l) -ge 1"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_input.usb-Solid_State_System_Co._Ltd._MMX_150-00.mono-fallback"
device_kind = "source"
on_click = "pactl set-source-mute alsa_input.usb-Solid_State_System_Co._Ltd._MMX_150-00.mono-fallback toggle"
if_command = "test $(pactl list cards short | grep MMX_150-00 | wc -l) -ge 1"

[[block]]
block = "backlight"
# only show when not on AC
if_command = "test $(cat /sys/class/power_supply/AC/online) -eq 0"

[[block]]
block = "time"
interval = 5
format = "%Y-%m-%d %H:%M:%S"

[[block]]
block = "battery"
full_threshold = 95
format = "{percentage} {time} ({power})"
full_format = "{percentage}"
if_command = "test -e /sys/class/power_supply/BAT0"
[block.theme_overrides]
good_bg = "#222D32"
good_fg = "#CFD8DC"
