---
window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 2
    y: 2

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

# https://github.com/alacritty/alacritty/wiki/Color-schemes
schemes:
  # Colors (Afterglow)
  afterglow: &afterglow
    # Default colors
    primary:
      background: '#2c2c2c'
      foreground: '#d6d6d6'

      dim_foreground:    '#dbdbdb'
      bright_foreground: '#d9d9d9'
      dim_background:    '#202020' # not sure
      bright_background: '#3a3a3a' # not sure

    # Cursor colors
    cursor:
      text:   '#2c2c2c'
      cursor: '#d9d9d9'

    # Normal colors
    normal:
      black:   '#1c1c1c'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#cacaca'

    # Bright colors
    bright:
      black:   '#636363'
      red:     '#bc5653'
      green:   '#909d63'
      yellow:  '#ebc17a'
      blue:    '#7eaac7'
      magenta: '#aa6292'
      cyan:    '#86d3ce'
      white:   '#f7f7f7'

    # Dim colors
    dim:
      black:   '#232323'
      red:     '#74423f'
      green:   '#5e6547'
      yellow:  '#8b7653'
      blue:    '#556b79'
      magenta: '#6e4962'
      cyan:    '#5c8482'
      white:   '#828282'


  # Colors (Ayu Mirage)
  ayu_mirage: &ayu_mirage
    # Default colors
    primary:
      background: '#202734'
      foreground: '#CBCCC6'

    # Normal colors
    normal:
      black: '#191E2A'
      red: '#FF3333'
      green: '#BAE67E'
      yellow: '#FFA759'
      blue: '#73D0FF'
      magenta: '#FFD580'
      cyan: '#95E6CB'
      white: '#C7C7C7'

    # Bright colors
    bright:
      black: '#686868'
      red: '#F27983'
      green: '#A6CC70'
      yellow: '#FFCC66'
      blue: '#5CCFE6'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'


  # Colors (Dracula)
  dracula: &dracula
    # Default colors
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'

    # Bright colors
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'


  # Colors (Material Theme)
  material: &material
    # Default colors
    primary:
      background: '#263238'
      foreground: '#eeffff'

    # Normal colors
    normal:
      black:   '#000000'  # Arbitrary
      red:     '#e53935'
      green:   '#91b859'
      yellow:  '#ffb62c'
      blue:    '#6182b8'
      magenta: '#ff5370'  # Dark pink of the original material theme
      cyan:    '#39adb5'
      white:   '#a0a0a0'  # Arbitrary

    # Bright colors
    bright:
      black:   '#4e4e4e'  # Arbitrary
      red:     '#ff5370'
      green:   '#c3e88d'
      yellow:  '#ffcb6b'
      blue:    '#82aaff'
      magenta: '#f07178'  # Pink of the original material theme
      cyan:    '#89ddff'
      white:   '#ffffff'  # Arbitrary


  # Colors (Monokai Dark)
  monokai_dark: &monokai_dark
    # Default colors
    primary:
      background: '#272822'
      foreground: '#F8F8F2'

    # Normal colors
    normal:
      black:   '#272822'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F8F8F2'

    # Bright colors
    bright:
      black:   '#75715E'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F9F8F5'


  # Colors (Oceanic Next)
  oceanic_next: &oceanic_next
    # Default colors
    primary:
      background: '#1b2b34'
      foreground: '#d8dee9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1b2b34'
      cursor: '#ffffff'

    # Normal colors
    normal:
      black:   '#343d46'
      red:     '#EC5f67'
      green:   '#99C794'
      yellow:  '#FAC863'
      blue:    '#6699cc'
      magenta: '#c594c5'
      cyan:    '#5fb3b3'
      white:   '#d8dee9'

    # Bright colors
    bright:
      black:   '#343d46'
      red:     '#EC5f67'
      green:   '#99C794'
      yellow:  '#FAC863'
      blue:    '#6699cc'
      magenta: '#c594c5'
      cyan:    '#5fb3b3'
      white:   '#d8dee9'


  # Colors (Solarized Dark)
  solarized_dark: &solarized_dark
    # Default colors
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0

    # Cursor colors
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3


  # Colors (Taerminal)
  taerminal: &taerminal
    # Default colors
    primary:
      background: '#26282a'
      foreground: '#f0f0f0'
    cursor:
      background: '#f0f0f0'
      foreground: '#26282a'

    # Normal colors
    normal:
      black:   '#26282a'
      red:     '#ff8878'
      green:   '#b4fb73'
      yellow:  '#fffcb7'
      blue:    '#8bbce5'
      magenta: '#ffb2fe'
      cyan:    '#a2e1f8'
      white:   '#f1f1f1'

    # Bright colors
    bright:
      black:   '#6f6f6f'
      red:     '#fe978b'
      green:   '#d6fcba'
      yellow:  '#fffed5'
      blue:    '#c2e3ff'
      magenta: '#ffc6ff'
      cyan:    '#c0e9f8'
      white:   '#ffffff'


  # Colors (Tender)
  tender: &tender
    # Default colors
    primary:
      background: '#282828'
      foreground: '#eeeeee'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#f43753'
      green:   '#c9d05c'
      yellow:  '#ffc24b'
      blue:    '#b3deef'
      magenta: '#d3b987'
      cyan:    '#73cef4'
      white:   '#eeeeee'

    # Bright colors
    bright:
      black:   '#4c4c4c'
      red:     '#f43753'
      green:   '#c9d05c'
      yellow:  '#ffc24b'
      blue:    '#b3deef'
      magenta: '#d3b987'
      cyan:    '#73cef4'
      white:   '#feffff'



colors: *ayu_mirage