[theme]
theme = "modern"
[theme.overrides]
#separator = ""
info_bg = "#222D32"
info_fg = "#449CDB"
good_bg = "#222D32"
good_fg = "#99b938"
warning_bg = "#222D32"
warning_fg = "#FE7E29"

[icons]
icons = "awesome4"

[[block]]
block = "external_ip"
format = "$ip "
interval = 3600
error_interval = 300

[[block]]
block = "net"
device = "enp39s0"
format = "$icon $ipv6 $ip ^icon_net_down$speed_down.eng(prefix:K,unit:b) ^icon_net_up$speed_up.eng(prefix:K,unit:b) "
missing_format = ""
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 7.0
alert = 5.0
format = "/ $available "

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
format = "/home $available "

[[block]]
block = "disk_space"
path = "/var"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 7.0
alert = 5.0
format = "/var $available "

[[block]]
block = "temperature"
chip = "amdgpu-*"
format = "$icon G: $average"
format_alt = "$icon G: $min min, $max max, $average avg "
inputs = ["edge", "junction", "mem"]
idle = 60
info = 80
warning = 95

[[block]]
block = "temperature"
chip = "k10temp-*"
format = "$icon C: $average"
format_alt = "$icon C: $min min, $max max, $average avg "
idle = 50
info = 60

[[block]]
block = "memory"
format = "$icon $mem_used $mem_used_percents "

[[block]]
block = "cpu"
interval = 5
format = "$icon $utilization $frequency "

[[block]]
block = "load"
interval = 5
format = "$icon $1m "
info = 1
warning = 8
critical = 16

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo"
device_kind = "sink"
format = "Ext: $volume "
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pactl set-sink-mute alsa_output.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo toggle"


[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo"
device_kind = "source"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pactl set-source-mute alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo toggle"

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.pci-0000_31_00.4.iec958-stereo"
device_kind = "sink"
format = "Opt: $volume"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pactl set-sink-mute alsa_output.pci-0000_31_00.4.iec958-stereo toggle"

[[block]]
block = "bluetooth"
mac = "98:7A:14:94:B6:94"
format = "$icon {$percentage|}"
disconnected_format = "$icon "
#on_click = "blueman-manager"

[[block]]
block = "time"
interval = 5
[block.format]
full = "$icon $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S')"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
