[theme]
name = "modern"
[theme.overrides]
separator = ""
info_bg = "#222D32"
info_fg = "#449CDB"
good_bg = "#222D32"
good_fg = "#99b938"
warning_bg = "#222D32"
warning_fg = "#FE7E29"

[icons]
name = "awesome"

[[block]]
block = "external_ip"
format = "{ip}"
interval = 3600
error_interval = 300

[[block]]
block = "net"
device = "enp39s0"
format = " {ipv6} {ip} ({bitrate}) {speed_down;K*b}{speed_up;K*b}"
interval = 5
hide_inactive = true
icons_format = "{icon}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{alias} {available}"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
format = "{alias} {available}"

[[block]]
block = "disk_space"
path = "/var"
alias = "/var"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0
format = "{alias} {available}"

[[block]]
block = "temperature"
chip = "amdgpu-*"
format = "G: {min} min, {max} max, {average} avg"
inputs = ["edge", "junction", "mem"]
idle = 60
info = 80
warning = 95

[[block]]
block = "temperature"
chip = "k10temp-*"
format = "C: {min} min, {max} max, {average} avg"
idle = 50
info = 60

[[block]]
block = "memory"
display_type = "memory"
#format_mem = "{mem_used_percents}"
format_mem = "{mem_used} {mem_used_percents}"
#format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 5
format = "{1m}"
info = 1
warning = 8
critical = 16

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo"
device_kind = "sink"
format = "Ext: {volume}"
on_click = "pactl set-sink-mute alsa_output.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo toggle"
show_volume_when_muted = true

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo"
device_kind = "source"
on_click = "pactl set-source-mute alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo toggle"
show_volume_when_muted = true

[[block]]
block = "sound"
driver = "pulseaudio"
name = "alsa_output.pci-0000_31_00.4.iec958-stereo"
device_kind = "sink"
format = "Opt: {volume}"
on_click = "pactl set-sink-mute alsa_output.pci-0000_31_00.4.iec958-stereo toggle"
show_volume_when_muted = true

[[block]]
block = "bluetooth"
mac = "98:7A:14:94:B6:94"
format = "{label}"
#on_click = "blueman-manager"

[[block]]
block = "time"
interval = 5
format = "%Y-%m-%d %H:%M:%S"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
